apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
         # - path: /mini-budget-tracker
         #   pathType: Prefix
         #   backend:
         #     service:
         #       name: mini-budget-tracker-service
         #       port:
         #         number: 3000
          - path: /nginx
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
          - path: /k8sgpt
            pathType: Prefix
            backend:
              service:
                name: k8sgpt-service
                port:
                  number: 80
          # Uncomment below to add Node.js service
          - path: /nodejs
            pathType: Prefix
            backend:
              service:
                name: nodejs-service
                port:
                  number: 3000
