apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /nodejs(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nodejs-service
                port:
                  number: 3000
          - path: /nginx(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
          - path: /k8sgpt(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: k8sgpt-service
                port:
                  number: 80
          # Add more apps here
          # - path: /mini-budget-tracker(/|$)(.*)
          #   pathType: ImplementationSpecific
          #   backend:
          #     service:
          #       name: mini-budget-tracker-service
          #       port:
          #         number: 3000
