apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /nodejs(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nodejs-service
                port:
                  number: 3000

          - path: /nginx(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nginx-service
                port:
                  number: 80

          # Metrics → service port 8081 (rewritten to /metrics)
          - path: /k8sgpt/metrics(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: k8sgpt-service
                port:
                  number: 8081

          # API → service port 80 (rewritten to /)
          - path: /k8sgpt(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: k8sgpt-service
                port:
                  number: 80
