---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mini-budget-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /mnt/data/mini-budget

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mini-budget-data
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi

---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: mini-budget-tracker
#  namespace: default
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: mini-budget-tracker
#  template:
#    metadata:
#      labels:
#        app: mini-budget-tracker
#    spec:
#      containers:
#      - name: mini-budget-tracker
#        image: "meetpatel1111/mini-budget-tracker:${ENVIRONMENT}"
#        ports:
#        - containerPort: 3000
#        volumeMounts:
#        - name: data-volume
#          mountPath: /data
#      volumes:
#      - name: data-volume
#        persistentVolumeClaim:
#          claimName: mini-budget-data

---
#apiVersion: v1
#kind: Service
#metadata:
#  name: mini-budget-tracker-service
#  namespace: default
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#spec:
#  selector:
#    app: mini-budget-tracker
#  type: ClusterIP
#  ports:
#    - port: 3000
#      targetPort: 3000

---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: main-ingress
#   namespace: default
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   ingressClassName: nginx
#   rules:
#     - http:
#         paths:
#           - path: /mini-budget-tracker
#             pathType: Prefix
#             backend:
#               service:
#                 name: mini-budget-tracker-service
#                 port:
#                   number: 3000