name: One-Click K8s Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev, test)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
      action:
        description: 'Terraform action (apply, destroy, refresh)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
          - refresh

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-k8s:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Verify kubectl version
        run: kubectl version --client

      - name: Configure AWS CLI
        run: |
          ENVIRONMENT="${{ github.event.inputs.environment }}"
          AWS_REGION="us-east-1"
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          if [[ "$ENVIRONMENT" == "dev" ]]; then
            TFVARS_FILE="dev.tfvars"
          else
            TFVARS_FILE="test.tfvars"
          fi
          echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV

      - name: Pre-bootstrap S3 & DynamoDB
        run: |
          ENVIRONMENT="${{ github.event.inputs.environment }}"
          ACTION="${{ github.event.inputs.action }}"
          AWS_REGION="us-east-1"
          chmod +x terraform/bootstrap/prebootstrap.sh
          ./terraform/bootstrap/prebootstrap.sh $ENVIRONMENT $AWS_REGION

      - name: Docker Login
        if: ${{ github.event.inputs.action == 'apply' }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Terraform Init (Remote S3 Backend)
        run: |
          cd terraform
          export AWS_REGION="us-east-1"
          terraform init -input=false -reconfigure \
            -backend-config="bucket=tf-state-${ENVIRONMENT}-state" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=$AWS_REGION" \
            -backend-config="dynamodb_table=terraform-locks-${ENVIRONMENT}"

      - name: Terraform Fmt
        run: |
          cd terraform
          terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Execute Terraform
        run: |
          cd terraform
          ACTION="${{ github.event.inputs.action }}"
          case "$ACTION" in
            apply)
              terraform plan -var-file="$TFVARS_FILE" -out=tfplan
              terraform apply tfplan
              ;;
            destroy)
              terraform plan -destroy -var-file="$TFVARS_FILE" -out=tfplan-destroy
              terraform apply -auto-approve tfplan-destroy
              ;;
            refresh)
              terraform refresh -var-file="$TFVARS_FILE"
              ;;
            *)
              echo "Unknown action: $ACTION"
              exit 1
              ;;
          esac

      - name: Build & Push Node.js App Image
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          NODEJS_IMAGE=$(grep nodejs_docker_image terraform/$TFVARS_FILE | awk -F'=' '{print $2}' | xargs)
          cd apps/nodejs-app
          docker build -t $NODEJS_IMAGE .
          docker push $NODEJS_IMAGE

      - name: Update kubeconfig
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          AWS_REGION=$(grep aws_region terraform/$TFVARS_FILE | awk -F'=' '{print $2}' | xargs)
          CLUSTER_NAME=$(terraform -chdir=terraform output -raw cluster_name)
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Apply Kubernetes Deployments * Services
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.13.0/deploy/static/provider/aws/deploy.yaml
          
          # Wait for NGINX controller pods to be ready
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=180s
          
          ENVIRONMENT="${{ github.event.inputs.environment }}" && cp k8s/k8s-deployments.yaml k8s/temp.yaml && envsubst < k8s/temp.yaml > k8s/k8s-deployments.yaml && rm k8s/temp.yaml && kubectl apply -f k8s/k8s-deployments.yaml
          ENVIRONMENT="${{ github.event.inputs.environment }}" && cp k8s/k8s-services.yaml k8s/temp.yaml && envsubst < k8s/temp.yaml > k8s/k8s-services.yaml && rm k8s/temp.yaml && kubectl apply -f k8s/k8s-services.yaml
          ENVIRONMENT="${{ github.event.inputs.environment }}" && cp k8s/ingress.yaml k8s/temp.yaml && envsubst < k8s/temp.yaml > k8s/ingress.yaml && rm k8s/temp.yaml && kubectl apply -f k8s/ingress.yaml
          
          # Wait for Ingress IP/Hostname
          echo "Waiting for Ingress endpoint..."
          INGRESS_NAME="main-ingress"
          for i in {1..30}; do
            EXTERNAL_IP=$(kubectl -n default get ingress $INGRESS_NAME -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            if [ -n "$EXTERNAL_IP" ]; then
              echo "Ingress ready: http://$EXTERNAL_IP"
              break
            fi
            echo "Waiting 10s..."
            sleep 10
          done
          
          # Fallback if still empty
          if [ -z "$EXTERNAL_IP" ]; then
            echo "Ingress hostname not ready yet. Check with: kubectl get ingress $INGRESS_NAME -n $NAMESPACE"
          fi
            
      - name: Verify Kubernetes Deployments & Services
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          kubectl get deployments -A
          kubectl get svc -A
        
