name: HPA Fortio stress test for autosclaling , scale-up and scale-down pods

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'EKS Cluster name'
        required: true
        default: 'eks-cluster-dev'
      region:
        description: 'AWS region'
        required: true
        default: 'us-east-1'
      namespace:
        description: 'Kubernetes namespace'
        required: true
        default: 'default'
      service_name:
        description: 'Target service name'
        required: true
        default: 'nodejs-service'
        type: choice
        options:
          - nodejs-service
          - nginx-service
          - k8sgpt-service
      path:
        description: 'Service endpoint path'
        required: true
        default: '/nodejs/'
        type: choice
        options:
          - '/nodejs/'
          - '/nginx/'
          - '/k8sgpt/'
      qps:
        description: 'Queries per second'
        required: true
        default: '500'
      load_duration:
        description: 'Duration of stress load (e.g., 120s)'
        required: true
        default: '120s'

jobs:
  hpa-stress-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest'

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig \
          --name ${{ github.event.inputs.cluster_name }} \
          --region ${{ github.event.inputs.region }}

    - name: Start Fortio Load (Scale-Up Trigger)
      run: |
        echo "Starting Fortio load for ${{ github.event.inputs.load_duration }} at ${{ github.event.inputs.qps }} QPS"
        kubectl run fortio-load \
          --image=fortio/fortio \
          -n ${{ github.event.inputs.namespace }} \
          --restart=Never \
          --command -- \
          fortio load -qps ${{ github.event.inputs.qps }} -t ${{ github.event.inputs.load_duration }} \
          http://${{ github.event.inputs.service_name }}.${{ github.event.inputs.namespace }}.svc.cluster.local:3000${{ github.event.inputs.path }} &

    - name: Watch HPA Scaling (During Load)
      run: |
        echo "Watching HPA during load..."
        timeout ${{ github.event.inputs.load_duration }} \
        kubectl get hpa -n ${{ github.event.inputs.namespace }} -w || true

    - name: Cleanup Fortio Pod
      if: always()
      run: |
        kubectl delete pod fortio-load -n ${{ github.event.inputs.namespace }} --ignore-not-found

    - name: Wait for Scale-Down Window
      run: |
        echo "Waiting 4 minutes 30 seconds to allow scale-down start (HPA stabilizationWindowSeconds=300)..."
        sleep 270

    - name: Watch HPA Scaling (Scale-Down)
      run: |
        echo "Watching HPA scale down..."
        timeout 120 \
        kubectl get hpa -n ${{ github.event.inputs.namespace }} -w || true

    - name: Watch Pods Scaling
      run: |
        echo "Watching pod count after load stops..."
        kubectl get pods -l app=nodejs-app -n ${{ github.event.inputs.namespace }}
